Fixed up the CI so that it will actually catch test PyPI failures in advance.
